import { Head } from "next/document"
import "./globals.css"
import "normalize.css/normalize.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta
          httpEquiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        />
      </Head>
      <body className="bg-[#F9FAFE]">{children}</body>
    </html>
  )
}
